[versions]
minecraft = "1.21"
moonshine = "2.0.4"
guice = "7.0.0"
configurate = "4.2.0-SNAPSHOT"
adventureSerializerConfigurate4 = "4.17.0"

# minecraft plugins
miniPlaceholders = "2.2.3"

# tests
junit = "5.10.3"

# gradle plugins
shadow = "8.1.8"
runPaper = "2.3.0"
resourceFactory = "1.1.2"

[libraries]
guice = { module = "com.google.inject:guice", version.ref = "guice" }
moonshine = { module = "net.kyori.moonshine:moonshine-standard", version.ref = "moonshine" }
configurate = { module = "org.spongepowered:configurate-hocon", version.ref = "configurate" }
adventureSerializerConfigurate4 = { module = "net.kyori:adventure-serializer-configurate4", version.ref = "adventureSerializerConfigurate4"}

# minecraft plugins
miniPlaceholders = { module = "io.github.miniplaceholders:miniplaceholders-api", version.ref = "miniPlaceholders" }

# tests
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }

[plugins]
shadow = { id = "io.github.goooler.shadow", version.ref = "shadow" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
resouceFactory = { id = "xyz.jpenilla.resource-factory-paper-convention", version.ref = "resourceFactory" }
